openapi: 3.0.3
info:
  title: Trie
  description: The documentation for the Trie used to manage searches.
  version: 1.0.0
servers:
  - url: 'http:/?localhost:8080'
paths:
  /api/search:
    get:
      summary: Get Titles
      description: Get a list of all titles matching the given prefix.
      responses:
        '200':
          description: There were one or more results with the specified prefix.
        '400':
          description: There were no results.
  
